name: 'Emily Murphy '
favicon: null
layout_spectrum: 0.83446
typography_spectrum: 0.14877173444256186
title: Emily Murphy Pottery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8f95b7'
    - '#fdb86d'
    - '#4b0d20'
    - '#d91f36'
  brandStrength: 0.16566130192950368
  lightness: 0.6998663162812591
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
